const mongoose=require('mongoose');
const Schema=mongoose.Schema
const orderSchema=new Schema({
    userId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'user'
    },
    shippingInfo:{
        name:{
            type:String,
            required:true
        },
        email:{
            type:String,
            required:true
        },
        address:{
            type:String,
            required:true
        },
        state:{
            type:String,
            required:true
        },
        postalCode:{
            type:Number,
            required:true
        },
        country:{
            type:String,
            required:true
        }
    },
    orderItems:[{
        name:{
            type:String,
            required:true
        },
        price:{
            type:Number,
            required:true
        },
        quantity:{
            type:Number,
            required:true
        },
        image:{
            type:String,
            required:true
        },
        productId:{
            type:mongoose.Schema.Types.ObjectId,
            ref:'product'
        }
    }],
    paymentInfo:{
        paymentId:{
            type:String
        },
        paymentType:{
            type:String
        },
        paymentStatus:{
            type:Boolean,
            default:false
        }
    },
    itemPrice:{
        type:Number,
        required:true,
        default:0
    },
    shippingPrice:{
        type:Number,
        required:true,
        default:0
    },
    taxPrice:{
        type:Number,
        required:true,
        default:0
    },
    totalPrice:{
        type:Number,
        required:true,
        default:0
    },
    orderStatus:{
        type:String,
        default:'Processing'
    },
    deliveredAt:{
        type:Date
    }
},{timestamps:true})

const orderModel=mongoose.model('Order',orderSchema)
module.exports=orderModel