const mongoose=require('mongoose')
const Schema=mongoose.Schema;
const productSchema=new Schema({
    userId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'user'
    },
    category:{
        categoryName:{
            type:String
        },
        categoryId:{
            type:mongoose.Schema.Types.ObjectId,
            ref:'category'
        }
    },
    productName:{
        type:String
    },
    wareHouse:{
        wareHouseName:{
            type:String
        },
        wareHouseId:{
            type:mongoose.Schema.Types.ObjectId,
            ref:'wareHouse'
        }
    },
    productFeatures:{
        type:String
    },
    productConsumptionTime:{
        type:String
    },
    taxes:{
        taxType:{
            type:String,
            default:'GST'
        },
        taxPercentage:{
            type:Number,
        }
    },
    rating:{
        number:{
        type:Number,
        default: 0
        },
        star:{
        type:Number,
        default: 0
            }
    },
    price:{
        purchasePrice:{
            type:Number
        },
        sellingPrice:{
            type:Number
        },
        discountPercentage:{
            type:Number
        },
        savingPrice:{
            type:Number
        }
    },
    specs:{
        specsName:{
            type:String
        },
        specsUnit:{
            type:String
        },
        weight:{
            type:Number
        },
        dimension:{
            type:String
        }
    },
    stock:{
        type:Number,
        required:true,
        default:1
    },
    originDetails:{
        origin:{
            type:String,
        },
        type:{
            type:String
        },
        certification:{
            type:String
        },
        mapImage:{
            type:String
        }
    },
    productIdentification:{
        skuNumber:{
            type:String
        },
        tiosNumber:{
            type:String
        }
    },
    productImage:{
        frontImage:{
            type:String
        },
        backImage:{
            type:String
        },
        galleryImages:{
            type:Array
        }
        },
    is_variation:{
        type:Boolean,
        default:false,
        required:true
        },
    processDetails:{
        processDescription:{
            type:String 
        },
        processDescription1:{
            type:String 
        },
        processDescription2:{
            type:String 
        },
        processDescription3:{
            type:String 
        },
        processDescription4:{
            type:String 
        },
        processImage:{
            type:Array
        }
    },
    status:{
        type:Boolean,
        default:true,
        required:true
    },
    isReturnable:{
        type:Boolean,
        default:false
    },

},{timestamps:true})

const productModel=mongoose.model('product',productSchema);
module.exports=productModel