const mongoose=require('mongoose');
const Schema=mongoose.Schema
const variationSchema=new Schema({
    productId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'product'
    },
    size:{
        type:String
    },
    color:{
        type:String
    },
    weight:{
        type:String
    },
    purchasePrice:{
        type:Number
    },
    sellingPrice:{
        type:Number
    },
    discountPercentage:{
        type:Number
    },
    savingPrice:{
        type:Number
    },
    stock:{
        type:Number
    },
    frontImage:{
        type:String
    },
    backImage:{
        type:String
    },
    galleryImages:{
        type:Array
    },
    dimension:{
        type:String
    },
    specs:{
        type:String
    },
    specsUnit:{
        type:String
    },
    weight1:{
        type:String
    },
    skuNumber:{
        type:String
    },
    tiosNumber:{
        type:String
    }
},{timestamps:true})

const variationModel=mongoose.model('productvariation',variationSchema)
module.exports=variationModel